export enum CardRank {
    'Two' = '2',
    'Three' = '3',
    'Four' = '4',
    'Five' = '5',
    'Six' = '6',
    'Seven' = '7',
    'Eight' = '8',
    'Nine' = '9',
    'Ten' = 'T',
    'Jack' = 'J',
    'Queen' = 'Q',
    'King' = 'K',
    'Ace' = 'A',
}

export const stringToCardRank: Record<string, CardRank> = {
    '2': CardRank.Two,
    '3': CardRank.Three,
    '4': CardRank.Four,
    '5': CardRank.Five,
    '6': CardRank.Six,
    '7': CardRank.Seven,
    '8': CardRank.Eight,
    '9': CardRank.Nine,
    'T': CardRank.Ten,
    'J': CardRank.Jack,
    'Q': CardRank.Queen,
    'K': CardRank.King,
    'A': CardRank.Ace,
};

export const allRanksArray: CardRank[] = [
    CardRank.Two,
    CardRank.Three,
    CardRank.Four,
    CardRank.Five,
    CardRank.Six,
    CardRank.Seven,
    CardRank.Eight,
    CardRank.Nine,
    CardRank.Ten,
    CardRank.Jack,
    CardRank.Queen,
    CardRank.King,
    CardRank.Ace,
];
