name: Deploy
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Copy app bundle
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "static/"
          target: "/root/poker/nginx/poker"
          strip_components: 1
          rm: true

      - name: Correct access rights
        run: chmod -R 755 /root/poker/nginx/poker
