name: Deploy
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Script
        run: echo ${{ secrets.VPS_HOST }}

      - name: Checkout the repo
        uses: actions/checkout@v4

#      - name: Build app
#        run: "npm run build"

      - name: Copy app bundle
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PORT: ${{ secrets.VPS_PORT }}
          KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        with:
          source: "./static"
          target: "~/poker/nginx/poker"

